### ISSUE TITLE
FYI: Spotify OSS page is out of date

### ISSUE THREAD

**Issue by GeorgeHahn** [itsmeow/Spicetify-Canvas#4]
The latest xpui build appears to use cef 4430. The current patch # can be obtained by running the following snippet: `navigator.appVersion.match(/.*Chrome\/([0-9\.]+)/)[1].split('.')[2]`

I have not had success with replacing the xpui cef build. Spotify launches with a blank window when I swap in my build.

**Comment by itsmeow** [comment]
README addresses this. You can also just use chrome://version in Chrome Tools.

**Comment by itsmeow** [comment]
I've had the same problem, I think it's because the branch is on a newer minor version than Spotify. I was trying to build the exact commit but my hard drive decided to crash and I'm giving it some rest. Try using the commit method in the README, let me know.

**Comment by itsmeow** [comment]
I tried running Spotify on an existing published build of CEF without MP4 (https://cef-builds.spotifycdn.com/index.html#windows32), the version was 90.6.6, Spotify is running 90.6.5. The build worked just fine, so it does mean Spotify is still patchable. Right now 4430's latest is on 90.6.7, which might break Spotify? I will download the 90.6.7 without MP4 build and try it out.

**Comment by GeorgeHahn** [comment]
Sorry, I completely missed the readme update! I'm running that build now and will report back.

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/119912537-a358c400-bf29-11eb-8a25-35ce0b4c6cba.png)
It runs on 90.6.7 just fine, so we must be missing some type of build argument that Spotify is not happy about.

I personally thought my issues were just because my hard drive was failing and giving bad data, but maybe my build was fine?
Did you use the new files? They changed the pak files required.

**Comment by itsmeow** [comment]
Also I noticed, the cefclient on my build doesn't work, so I don't see why Spotify would work with it either. Downloaded builds client works just fine.
![image](https://user-images.githubusercontent.com/10366817/119912803-211ccf80-bf2a-11eb-9c72-cf5f98635fb7.png)
Does yours work?

**Comment by GeorgeHahn** [comment]
I noticed the file change but didn't try to find out which were required - I just dropped my whole build folder into the spotify directory. One moment, I'll test cefclient.

**Comment by GeorgeHahn** [comment]
Nope, my cefclient is broken identically.

**Comment by itsmeow** [comment]
Maybe `enable_nacl=false blink_symbol_level=0 symbol_level=0` is to blame?

**Comment by itsmeow** [comment]
It appears the recommended args for automated builds are the following (and likely what Spotify uses as well):
![image](https://user-images.githubusercontent.com/10366817/119913049-e49da380-bf2a-11eb-9a3f-ba6fbd28183f.png)
Source: https://bitbucket.org/chromiumembedded/cef/wiki/AutomatedBuildSetup.md

I also found this thread, and I *also* have been having the make_distrib failure. This is probably it!
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=18346&start=10

**Comment by itsmeow** [comment]
I'll add `use_thin_lto=false` to the README, I think the nacl + symbols are safe for now, since no one explicitly mentioned them. I have no idea what `use_thin_lto=false` does, but we'll see. Try building that, let me know. I'm not gonna mess with it has my external hard drive with CEF's source on it is on its last legs.

**Comment by itsmeow** [comment]
Found the related Chromium bug. Weird issue. https://bugs.chromium.org/p/chromium/issues/detail?id=1177001

**Comment by GeorgeHahn** [comment]
Good find! I restarted my build with that flag set and will keep an eye on the upstream issue.

**Comment by itsmeow** [comment]
You may be able to use the patch method without a full rebuild. Look at the new section of the README on re-using the CEF build folder.

**Comment by GeorgeHahn** [comment]
I wish I could; I delete the source directory after each build 😬

**Comment by GeorgeHahn** [comment]
I'll be back in a few hours, hopefully with good news!

**Comment by GeorgeHahn** [comment]
Confirmed - a build at `7a604aa` without thin LTO works.

I just updated to the latest VS 2019 build tools and will try a build with LTO turned back on.

**Comment by GeorgeHahn** [comment]
Nope, the same commit with thinlto enabled on the latest 2019 build tools is broken.

**Comment by itsmeow** [comment]
I don't see why a newer VS would fix it, seeing as the chromium bug is not related to the build tools but ThinLTO itself

**Comment by GeorgeHahn** [comment]
The build tools include the compiler; an updated compiler may fix thinlto.
